version: '3'
services:
  client:
    image: odex-client:latest
    container_name: "client"
    environment:
      - REACT_APP_ENGINE_HTTP_URL=http://matching-engine:8081
      - REACT_APP_ENGINE_WS_URL=ws://matching-engine:8081
      - REACT_APP_DEFAULT_NETWORK_ID=8888
    command: [ 'REACT_APP_DEFAULT_NETWORK_ID=8888', 'yarn', 'serve']